//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Expense
    {
        public int ExpenseId { get; set; }
        public string Description { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string CategoryName { get; set; }
        public int CategoryId { get; set; }
    }
}
